// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Neural Mastery's sidebar is grouped explicitly rather than left as one flat
 * autogenerated list, now that the site has grown to ~28 top-level sections.
 * Each group below wraps one or more docs folders via {type:'autogenerated',
 * dirName: '<folder>'} - no files were moved, no URLs changed; this only
 * changes how the sidebar visually groups and orders them. Order within a
 * group is controlled by the array order here (not each folder's own
 * _category_.json position, which now only orders pages *within* that
 * folder).
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Foundations',
      link: { type: 'generated-index', description: 'Systems, Python, and math fundamentals — before any AI-specific content.' },
      items: [
        { type: 'autogenerated', dirName: 'cs-fundamentals' },
        { type: 'autogenerated', dirName: 'python-engineering' },
        { type: 'autogenerated', dirName: 'mathematics-for-ai' },
      ],
    },
    {
      type: 'category',
      label: 'Models',
      link: { type: 'generated-index', description: 'Classical ML through modern LLMs — every model family covered in depth.' },
      items: [
        { type: 'autogenerated', dirName: 'machine-learning' },
        { type: 'autogenerated', dirName: 'deep-learning' },
        { type: 'autogenerated', dirName: 'computer-vision' },
        { type: 'autogenerated', dirName: 'nlp' },
        { type: 'autogenerated', dirName: 'speech-audio' },
        { type: 'autogenerated', dirName: 'llms-genai' },
        { type: 'autogenerated', dirName: 'graph-ml' },
        { type: 'autogenerated', dirName: 'reinforcement-learning' },
      ],
    },
    {
      type: 'category',
      label: 'Agents & Applications',
      link: { type: 'generated-index', description: 'Agentic systems, and where AI meets specific domains — science, healthcare, and beyond.' },
      items: [
        { type: 'autogenerated', dirName: 'agents' },
        { type: 'autogenerated', dirName: 'ai-for-science' },
        { type: 'autogenerated', dirName: 'domain-applications' },
      ],
    },
    {
      type: 'category',
      label: 'Systems & Infrastructure',
      link: { type: 'generated-index', description: 'Designing, building, and running production ML/AI systems at scale.' },
      items: [
        { type: 'autogenerated', dirName: 'ml-system-design' },
        { type: 'autogenerated', dirName: 'mlops' },
        { type: 'autogenerated', dirName: 'databases' },
        { type: 'autogenerated', dirName: 'frameworks' },
      ],
    },
    {
      type: 'category',
      label: 'Safety & Evaluation',
      link: { type: 'generated-index', description: 'Knowing whether a system is good, secure, and safe — not just whether it runs.' },
      items: [
        { type: 'autogenerated', dirName: 'ai-evaluation' },
        { type: 'autogenerated', dirName: 'ai-security' },
        { type: 'autogenerated', dirName: 'ai-safety' },
        { type: 'autogenerated', dirName: 'interpretability' },
      ],
    },
    {
      type: 'category',
      label: 'Research & Build',
      link: { type: 'generated-index', description: 'Reading the literature, and building real things — from scratch, and as full projects.' },
      items: [
        { type: 'autogenerated', dirName: 'research-engineering' },
        { type: 'autogenerated', dirName: 'build-from-scratch' },
        { type: 'autogenerated', dirName: 'projects' },
        { type: 'autogenerated', dirName: 'visual-lab' },
      ],
    },
    {
      type: 'category',
      label: 'Career',
      link: { type: 'generated-index', description: 'Tying everything together into a learning path and interview readiness.' },
      items: [
        { type: 'autogenerated', dirName: 'interview-prep' },
        { type: 'autogenerated', dirName: 'roadmaps' },
        { type: 'autogenerated', dirName: 'resources' },
      ],
    },
  ],
};

export default sidebars;
